keybinds:
  count: <space>
  new-clip: <shift> + s
counter:
  hold-multiplier: 2 # multiply keystrokes while holding by this
  hold-delay: 0.1 # the delay between repeated hold keystrokes
font: fontname.ttf
output:
  width: 500
  height: 200
  fps: 60
  fontsize: 200